# Model parameters
model: vit_tiny_patch4

# Training parameters
batch_size: 512
epochs: 100
accum_iter: 1

# Optimizer parameters
weight_decay: 0
lr: 1
blr: 0.1
min_lr: 0.0
warmup_epochs: 10

# Dataset parameters
data_path: ./data
nb_classes: 10

# Device parameters
device: cuda
seed: 0

# Distributed training parameters
world_size: 1
dist_url: env://

